// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2619.PlyBot2019.subsystems;


import org.usfirst.frc2619.PlyBot2019.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DigitalInput;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class SensorBar extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private DigitalInput sensorFarLeft;
    private DigitalInput sensorLeft;
    private DigitalInput sensorMiddle;
    private DigitalInput sensorRight;
    private DigitalInput sensorFarRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public DigitalInput[] sensBar = new DigitalInput[5];


    public SensorBar() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        sensorFarLeft = new DigitalInput(0);
        addChild("sensorFarLeft",sensorFarLeft);
        
        
        sensorLeft = new DigitalInput(1);
        addChild("sensorLeft",sensorLeft);
        
        
        sensorMiddle = new DigitalInput(2);
        addChild("sensorMiddle",sensorMiddle);
        
        
        sensorRight = new DigitalInput(3);
        addChild("sensorRight",sensorRight);
        
        
        sensorFarRight = new DigitalInput(4);
        addChild("sensorFarRight",sensorFarRight);
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        sensBar[0] = sensorFarLeft;
        sensBar[1] = sensorLeft;
        sensBar[2] = sensorMiddle;
        sensBar[3] = sensorRight;
        sensBar[4] = sensorFarRight;

    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        SmartDashboard.putBoolean("Sensor 0 On", !sensBar[0].get());
        SmartDashboard.putBoolean("Sensor 1 On", sensBar[1].get());

        SmartDashboard.putBoolean("Sensor 2 On", sensBar[2].get());
        SmartDashboard.putBoolean("Sensor 3 On", sensBar[3].get());
      
        SmartDashboard.putBoolean("Sensor 4 On", !sensBar[4].get());
        //Need 0 and 4
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
    public DigitalInput getSensor(int sensor){
        return sensBar[sensor];
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

